const affiliates = [
    { value: "Almeida Theatre", label: "Almeida Theatre" },
    { value: "Arcola Theatre", label: "Arcola Theatre" },
    { value: "Arts Theatre", label: "Arts Theatre" },
    { value: "Bloomsbury Theatre", label: "Bloomsbury Theatre" },
    { value: "Bush Theatre", label: "Bush Theatre" },
    { value: "Bridge Theatre", label: "Bridge Theatre" },
    { value: "Cadogan Hall Theatre", label: "Cadogan Hall Theatre" },
    { value: "Charing Cross Theatre", label: "Charing Cross Theatre" },
    { value: "Donmar Warehouse", label: "Donmar Warehouse" },
    { value: "Greenwich Theatre", label: "Greenwich Theatre" },
    { value: "Hackney Empire", label: "Hackney Empire" },
    { value: "Hampstead Theatre", label: "Hampstead Theatre" },
    { value: "Kiln Theatre", label: "Kiln Theatre" },
    { value: "Lyric Hammersmith Theatre", label: "Lyric Hammersmith Theatre" },
    { value: "Menier Chocolate Factory", label: "Menier Chocolate Factory" },
    { value: "New Wimbledon Theatre", label: "New Wimbledon Theatre" },
    { value: "Orange Tree Theatre", label: "Orange Tree Theatre" },
    { value: "Park Theatre", label: "Park Theatre" },
    { value: "Peacock Theatre", label: "Peacock Theatre" },
    { value: "Polka Theatre", label: "Polka Theatre" },
    { value: "Riverside Studios", label: "Riverside Studios" },
    { value: "Rose Theatre", label: "Rose Theatre" },
    { value: "The Other Palace", label: "The Other Palace" },
    { value: "Theatre Royal Stratford East", label: "Theatre Royal Stratford East" },
    { value: "Young Vic", label: "Young Vic" },
];

export default affiliates;
