const affiliates = [
    { value: "Almeida", label: "Almeida" },
    { value: "Arcola", label: "Arcola" },
    { value: "Arts", label: "Arts" },
    { value: "Bloomsbury", label: "Bloomsbury" },
    { value: "Bush", label: "Bush" },
    { value: "Bridge", label: "Bridge" },
    { value: "Cadogan Hall", label: "Cadogan Hall" },
    { value: "Charing Cross Theatre", label: "Charing Cross Theatre" },
    { value: "Donmar Warehouse", label: "Donmar Warehouse" },
    { value: "Greenwich", label: "Greenwich" },
    { value: "Hackney Empire", label: "Hackney Empire" },
    { value: "Hampstead", label: "Hampstead" },
    { value: "Kiln", label: "Kiln" },
    { value: "Lyric Hammersmith", label: "Lyric Hammersmith" },
    { value: "Menier Chocolate Factory", label: "Menier Chocolate Factory" },
    { value: "New Wimbledon Theatre", label: "New Wimbledon Theatre" },
    { value: "Orange Tree Theatre", label: "Orange Tree Theatre" },
    { value: "Park", label: "Park" },
    { value: "Peacock", label: "Peacock" },
    { value: "Polka", label: "Polka" },
    { value: "Riverside Studios", label: "Riverside Studios" },
    { value: "Rose Theatre", label: "Rose Theatre" },
    { value: "Soho", label: "Soho" },
    { value: "The Other Palace", label: "The Other Palace" },
    { value: "Theatre Royal Stratford East", label: "Theatre Royal Stratford East" },
    { value: "Young Vic", label: "Young Vic" },
];

export default affiliates;
