export const headers = [
    "Day",
    "Date",
    "P",
    "Venue",
    "AffiliateVenue",
    "OtherVenue",
    "VenueIsTba",
    "TitleOfShow",
    "ShowTitleIsTba",
    "Producer",
    "PressContact",
    "DateBkd",
    "IsSeasonGala",
    "IsOperaDance",
    "UserId",
    "TimeStamp",
];
