import { RequestData } from '@/lib/types'
const testData: RequestData = {
    "Year": 2024,
    "Range": "A1:N150",
    "Dates": {
        "01/06/2024": {
            "A2:H2": {
                "Day": "Saturday",
                "Date": "01/06/2024",
                "P": "",
                "Venue": "",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Test",
                "ShowIsTitleTba": "",
                "Producer": "",
                "PressContact": "",
                "DateBkd": "",
                "UserId": 34938493,
                "IsSeasonGala": 0,
                "IsOperaDance": 0
            }
        },
        "02/06/2024": {
            "A3:H3": {
                "Day": "Sunday",
                "Date": "02/06/2024",
                "P": "",
                "Venue": "",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "",
                "ShowIsTitleTba": "",
                "Producer": "",
                "PressContact": "",
                "DateBkd": "",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "03/06/2024": {
            "A4:H4": {
                "Day": "Monday",
                "Date": "03/06/2024",
                "P": "",
                "Venue": "King's Head Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Houdini's Greatest Escape",
                "ShowIsTitleTba": "",
                "Producer": "New Old Friends",
                "PressContact": "becky@bmpr.co.uk",
                "DateBkd": "22/04/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "04/06/2024": {
            "A5:H5": {
                "Day": "Tuesday",
                "Date": "04/06/2024",
                "P": "",
                "Venue": "ROYAL OPERA HOUSE MAIN STAGE",
                "OtherVenue": " ",
                "VenueIsTba": "",
                "TitleOfShow": "The Sarasota Ballet",
                "ShowIsTitleTba": "",
                "Producer": "The Sarasota Ballet",
                "PressContact": "Ashley.Woodfield@roh.org.uk",
                "DateBkd": "21/06/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A6:H6": {
                "Day": "",
                "Date": "04/06/2024",
                "P": "",
                "Venue": "Haymarket, Theatre Royal",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "A View From The Bridge",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "lewis.jenkins@storyhousepr.co.uk",
                "DateBkd": 45421,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A7:H7": {
                "Day": "",
                "Date": "04/06/2024",
                "P": "",
                "Venue": "Sadler's Wells ",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Rocío Molina Al Fondo Riela ",
                "ShowIsTitleTba": "",
                "Producer": "Sadler's Wells",
                "PressContact": "andrea.gillespie@sadlerswells.com",
                "DateBkd": 45419,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "05/06/2024": {
            "A8:H8": {
                "Day": "Wednesday",
                "Date": "05/06/2024",
                "P": "",
                "Venue": "ORANGE TREE THEATRE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Suite In 3 Keys",
                "ShowIsTitleTba": "",
                "Producer": "Orange Tree Theatre",
                "PressContact": "katiemd@katemorleypr.com",
                "DateBkd": 45056,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A9:H9": {
                "Day": "",
                "Date": "05/06/2024",
                "P": "",
                "Venue": "Ambassadors Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Kathy and Stella Solve a Murder!",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "chloe@aboutgracepr.com, laura@aboutgracepr.com",
                "DateBkd": "15/01/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A10:H10": {
                "Day": "",
                "Date": "05/06/2024",
                "P": "",
                "Venue": "Purcell Room, Southbank Centre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "LIFT Festival: The Land Acknowledgement or As You Like It",
                "ShowIsTitleTba": "",
                "Producer": "LIFT",
                "PressContact": "chloe@breadandbutterpr.uk",
                "DateBkd": "22/03/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A11:H11": {
                "Day": "",
                "Date": "05/06/2024",
                "P": "",
                "Venue": "Sadler's Wells",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Vicente Amigo In Concert ",
                "ShowIsTitleTba": "",
                "Producer": "Sadler's Wells",
                "PressContact": "andrea.gillespie@sadlerswells.com",
                "DateBkd": 45419,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A12:H12": {
                "Day": "",
                "Date": "05/06/2024",
                "P": "",
                "Venue": "Theatre Royal Windsor",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Accolade",
                "ShowIsTitleTba": "",
                "Producer": "Theatre Royal Windsor and Bill Kenwright Ltd",
                "PressContact": "development@theatreroyalwindsor.co.uk",
                "DateBkd": 45433,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "06/06/2024": {
            "A13:H13": {
                "Day": "Thursday",
                "Date": "06/06/2024",
                "P": "",
                "Venue": "Royal Opera House Main Stage",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Les Rendezvous / The Dream / Rhapsody",
                "ShowIsTitleTba": "",
                "Producer": "The Royal Ballet",
                "PressContact": "Ashley.Woodfield@roh.org.uk",
                "DateBkd": "21/06/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A14:H14": {
                "Day": "",
                "Date": "06/06/2024",
                "P": " ",
                "Venue": "Lyric Hammersmith",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Wedding Band: A Love/Hate Story in Black and White",
                "ShowIsTitleTba": "",
                "Producer": "Lyric Hammersmith Theatre",
                "PressContact": "burte.tsogbadrakh@lyric.co.uk",
                "DateBkd": 45239,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A15:H15": {
                "Day": "",
                "Date": "06/06/2024",
                "P": "",
                "Venue": "Chiswick House and Gardens",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Giffords Circus",
                "ShowIsTitleTba": "",
                "Producer": "Giffords Circus",
                "PressContact": "Kevin Wilson 07884 368697 kevinwilsonpr@gmail.com",
                "DateBkd": 45087,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A16:H16": {
                "Day": "",
                "Date": "06/06/2024",
                "P": "",
                "Venue": "Kiln Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "English (7pm)",
                "ShowIsTitleTba": "",
                "Producer": "Kiln Theatre",
                "PressContact": "kate@katemorleypr.com",
                "DateBkd": "30/10/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A17:H17": {
                "Day": "",
                "Date": "06/06/2024",
                "P": "",
                "Venue": "King's Head Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Diva: Live From Hell!",
                "ShowIsTitleTba": "",
                "Producer": "Blair Russell Productions",
                "PressContact": "hello@michellemangan.com ",
                "DateBkd": "14/03/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A18:H18": {
                "Day": "",
                "Date": "06/06/2024",
                "P": "",
                "Venue": "Southwark Playhouse Elephant",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "No Love Songs",
                "ShowIsTitleTba": "",
                "Producer": "Dundee Rep",
                "PressContact": "benw@breadandbutterpr.uk, 07791183043",
                "DateBkd": 45415,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A19:H19": {
                "Day": "",
                "Date": "06/06/2024",
                "P": "",
                "Venue": "Omnibus Theatre (Part of 96 Festival)",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Joe Carstairs",
                "ShowIsTitleTba": "",
                "Producer": "StoneCrabs Theatre",
                "PressContact": "annabelle@mobiusindustries.com",
                "DateBkd": 45419,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A20:H20": {
                "Day": "",
                "Date": "06/06/2024",
                "P": "",
                "Venue": "Sadler's Wells",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Alfonso Losa & Patricia Guerrero Alter Ego ",
                "ShowIsTitleTba": "",
                "Producer": "Sadler's Wells",
                "PressContact": "andrea.gillespie@sadlerswells.com",
                "DateBkd": 45053,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "07/06/2024": {
            "A21:H21": {
                "Day": "Friday",
                "Date": "07/06/2024",
                "P": "",
                "Venue": "ROYAL OPERA HOUSE MAIN STAGE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Dream / Short Works / Rhapsody",
                "ShowIsTitleTba": "",
                "Producer": "The Royal Ballet",
                "PressContact": "Ashley.Woodfield@roh.org.uk",
                "DateBkd": "21/06/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A22:H22": {
                "Day": "",
                "Date": "07/06/2024",
                "P": "",
                "Venue": "Leeds Playhouse",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "My Fair Lady",
                "ShowIsTitleTba": "",
                "Producer": "Leeds Playhouse/Opera North",
                "PressContact": "Rachel.marriner@leedsplayhouse.org.uk/07729 206332 \n",
                "DateBkd": 45400,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A23:H23": {
                "Day": "",
                "Date": "07/06/2024",
                "P": "",
                "Venue": "Sadler's Wells",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Eva Yerbabuena Yerbagüena (bright dark) ",
                "ShowIsTitleTba": "",
                "Producer": "Sadler's Wells",
                "PressContact": "andrea.gillespie@sadlerswells.com",
                "DateBkd": 45053,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A24:H24": {
                "Day": "Saturday",
                "Date": "07/06/2024",
                "P": "",
                "Venue": "",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "",
                "ShowIsTitleTba": "",
                "Producer": "",
                "PressContact": "",
                "DateBkd": "",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "09/06/2024": {
            "A25:H25": {
                "Day": "Sunday",
                "Date": "09/06/2024",
                "P": "",
                "Venue": "GLYNDEBOURNE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Merry Widow",
                "ShowIsTitleTba": "",
                "Producer": "Glyndebourne Productions Ltd",
                "PressContact": "kate.harvey@glyndebourne.com, 01273 102 307",
                "DateBkd": "22/08/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A26:H26": {
                "Day": "",
                "Date": "09/06/2024",
                "P": "",
                "Venue": "Sadler's Wells",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Israel Fernández ft. Diego del Morao In Concert – Pura Sangre ",
                "ShowIsTitleTba": "",
                "Producer": "Sadler's Wells",
                "PressContact": "andrea.gillespie@sadlerswells.com",
                "DateBkd": 45053,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "10/06/2024": {
            "A27:H27": {
                "Day": "Monday",
                "Date": "10/06/2024",
                "P": "",
                "Venue": "Jermyn Street Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Being Mr Wickham",
                "ShowIsTitleTba": "",
                "Producer": "Original Theatre",
                "PressContact": "alison@aduguidpr.co.uk / 07934 375492",
                "DateBkd": "25/03/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A28:H28": {
                "Day": "",
                "Date": "10/06/2024",
                "P": "",
                "Venue": "Sadler's Wells",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "David Coria & David Lagos Company ¡Fandango! ",
                "ShowIsTitleTba": "",
                "Producer": "Sadler's Wells",
                "PressContact": "andrea.gillespie@sadlerswells.com",
                "DateBkd": 45053,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "11/06/2024": {
            "A29:H29": {
                "Day": "Tuesday",
                "Date": "11/06/2024",
                "P": "",
                "Venue": "Barbican Autumn Season annnouncement",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Barbican Autumn Season annnouncement",
                "ShowIsTitleTba": "",
                "Producer": "Barbican Autumn Season annnouncement",
                "PressContact": "hbl@barbican.org.uk",
                "DateBkd": 45432,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A30:H30": {
                "Day": "",
                "Date": "11/06/2024",
                "P": "",
                "Venue": "ROYAL OPERA HOUSE LINBURY THEATRE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Next Generation Festival",
                "ShowIsTitleTba": "",
                "Producer": "The Royal Ballet",
                "PressContact": "Ashley.Woodfield@roh.org.uk",
                "DateBkd": "21/06/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A31:H31": {
                "Day": "",
                "Date": "11/06/2024",
                "P": "",
                "Venue": "Science Gallery London",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "LIFT: Bat Night Malarkey",
                "ShowIsTitleTba": "",
                "Producer": "LIFT",
                "PressContact": "chloe@breadandbutterpr.uk",
                "DateBkd": "22/03/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A32:H32": {
                "Day": "",
                "Date": "11/06/2024",
                "P": "",
                "Venue": "BRISTOL OLD VIC",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "A Child Of Science",
                "ShowIsTitleTba": "",
                "Producer": "Bristol Old Vic/Impossible",
                "PressContact": "Amanda Adams, amanda.adams@bristololdvic.org.uk",
                "DateBkd": 45118,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A33:H33": {
                "Day": "",
                "Date": "11/06/2024",
                "P": "",
                "Venue": "Almeida Theatre ",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "TBA",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "zinnes@almeida.co.uk",
                "DateBkd": 45119,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A34:H34": {
                "Day": "",
                "Date": "11/06/2024",
                "P": "",
                "Venue": "Park Theatre (Park90)",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Miss Julie",
                "ShowIsTitleTba": "",
                "Producer": "Lidless Theatre & Zoe Weldon & Ross Chandler in association with Park Theatre",
                "PressContact": "kevinwilsonpr@gmail.com ",
                "DateBkd": "25/03/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "12/06/2024": {
            "A35:H35": {
                "Day": "Wednesday",
                "Date": "12/06/2024",
                "P": "",
                "Venue": "ROYAL ALBERT HALL",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Swan Lake in-the-round",
                "ShowIsTitleTba": "",
                "Producer": "English National Ballet",
                "PressContact": "ines.carvalho@ballet.org.uk",
                "DateBkd": 44988,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A36:H36": {
                "Day": "",
                "Date": "12/06/2024",
                "P": "",
                "Venue": "The Other Palace",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Babies – A New(born) Musical",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "chloe@aboutgracepr.com",
                "DateBkd": "",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A37:H37": {
                "Day": "",
                "Date": "12/06/2024",
                "P": "",
                "Venue": "Royal Shakespeare Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Merry Wives Of Windsor",
                "ShowIsTitleTba": "",
                "Producer": "RSC",
                "PressContact": "dean.asker@rsc.org.uk ",
                "DateBkd": "14/07/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A38:H38": {
                "Day": "",
                "Date": "12/06/2024",
                "P": "",
                "Venue": "PITLOCHRY FESTIVAL THEATRE (12pm)",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Beautiful: The Carole King Musical",
                "ShowIsTitleTba": "",
                "Producer": "Pitlochry Festival Theatre",
                "PressContact": "duncanclarkepr@gmail.com / 0788093750",
                "DateBkd": "25/09/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A39:H39": {
                "Day": "",
                "Date": "12/06/2024",
                "P": "",
                "Venue": "PITLOCHRY FESTIVAL THEATRE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Nan Shepherd: Naked and Unashamed",
                "ShowIsTitleTba": "",
                "Producer": "Pitlochry Festival Theatre",
                "PressContact": "duncanclarkepr@gmail.com / 0788093750",
                "DateBkd": "25/09/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A40:H40": {
                "Day": "",
                "Date": "12/06/2024",
                "P": "",
                "Venue": "Queen Elizabeth Hall, Southbank Centre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "LIFT Festival: L'Homme rare",
                "ShowIsTitleTba": "",
                "Producer": "LIFT",
                "PressContact": "chloe@breadandbutterpr.uk",
                "DateBkd": "13/03/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A41:H41": {
                "Day": "",
                "Date": "12/06/2024",
                "P": "",
                "Venue": "Formosa Garden, W9",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "All's Well That Ends Well",
                "ShowIsTitleTba": "",
                "Producer": "Shakespeare in the Squares",
                "PressContact": "francesca@distriktlondon.com",
                "DateBkd": 45394,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A42:H42": {
                "Day": "",
                "Date": "12/06/2024",
                "P": "",
                "Venue": "Sadler's Wells",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Ballet Nacional de España Invocación ",
                "ShowIsTitleTba": "",
                "Producer": "Sadler's Wells",
                "PressContact": "andrea.gillespie@sadlerswells.com",
                "DateBkd": 45053,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "13/06/2024": {
            "A43:H43": {
                "Day": "Thursday",
                "Date": "13/06/2024",
                "P": "P",
                "Venue": "DONMAR WAREHOUSE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "TBA",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "georgie@katemorleypr.com",
                "DateBkd": "23/02/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A44:H44": {
                "Day": "",
                "Date": "13/06/2024",
                "P": "",
                "Venue": "CHISWICK HOUSE AND GARDENS",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Giffords Circus",
                "ShowIsTitleTba": "",
                "Producer": "Giffords Circus",
                "PressContact": "Kevin Wilson 07884 368697 kevinwilsonpr@gmail.com",
                "DateBkd": 45087,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A45:H45": {
                "Day": "",
                "Date": "13/06/2024",
                "P": "",
                "Venue": "CHICHESTER MINERVA THEATRE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Caretaker",
                "ShowIsTitleTba": "",
                "Producer": "Chichester Festival Theatre",
                "PressContact": "lucinda.morrison@cft.org.uk",
                "DateBkd": "20/10/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A46:H46": {
                "Day": "",
                "Date": "13/06/2024",
                "P": "",
                "Venue": "LIVERPOOL EVERYMAN",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Tell Me How It Ends",
                "ShowIsTitleTba": "",
                "Producer": "Liverpool Everyman",
                "PressContact": "shippen.martin@gmail.com",
                "DateBkd": 45627,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A47:H47": {
                "Day": "",
                "Date": "13/06/2024",
                "P": "",
                "Venue": "Finborough Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Kafka",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "mcpneil@gmail.com",
                "DateBkd": "23/02/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A48:H48": {
                "Day": "",
                "Date": "13/06/2024",
                "P": "",
                "Venue": "The Coronet Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Caryl Churchill’s L'amore Del Cuore (Heart's Desire)",
                "ShowIsTitleTba": "",
                "Producer": "Lacasadargilla",
                "PressContact": "Sharon@keanlanyon.com   Tel: 07973 843133",
                "DateBkd": 45412,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "14/06/2024": {
            "A49:H49": {
                "Day": "Friday",
                "Date": "14/06/2024",
                "P": "",
                "Venue": "PITLOCHRY FESTIVAL THEATRE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Footloose",
                "ShowIsTitleTba": "",
                "Producer": "Pitlochry Festival Theatre",
                "PressContact": "duncanclarkepr@gmail.com / 0788093750",
                "DateBkd": "25/09/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A50:H50": {
                "Day": "",
                "Date": "14/06/2024",
                "P": "",
                "Venue": "Finborough Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Kafka",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "mcpneil@gmail.com",
                "DateBkd": "23/02/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A51:H51": {
                "Day": "",
                "Date": "14/06/2024",
                "P": "",
                "Venue": "Brixton House",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "LIFT Festival: The Trials and Passions of Unfamous Women",
                "ShowIsTitleTba": "",
                "Producer": "LIFT",
                "PressContact": "ben@breadandbutterpr.uk",
                "DateBkd": "22/03/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A52:H52": {
                "Day": "",
                "Date": "14/06/2024",
                "P": "",
                "Venue": "Upstairs at the Gatehouse",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Longitude",
                "ShowIsTitleTba": "",
                "Producer": "Kaz Moloney",
                "PressContact": "Phoebe Carlisle – phoebe@chloenelkinconsulting.com, 07581619619",
                "DateBkd": 45394,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A53:H53": {
                "Day": "",
                "Date": "14/06/2024",
                "P": "",
                "Venue": "Sadler's Wells - Lilian Baylis Studio (6pm)",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Sara Jimenez, Ave de Plata",
                "ShowIsTitleTba": "",
                "Producer": "Sadler's Wells",
                "PressContact": "andrea.gillespie@sadlerswells.com",
                "DateBkd": 45419,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A54:H54": {
                "Day": "",
                "Date": "14/06/2024",
                "P": "",
                "Venue": "The Plaza, Port Talbot",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Dumpy Biscuit",
                "ShowIsTitleTba": "",
                "Producer": "The Other Room",
                "PressContact": "alice@otherroomtheatre.com",
                "DateBkd": 45422,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "15/06/2024": {
            "A55:H55": {
                "Day": "Saturday",
                "Date": "15/06/2024",
                "P": "",
                "Venue": "WALES MILLENNIUM CENTRE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Il trittico",
                "ShowIsTitleTba": "",
                "Producer": "Welsh National Opera",
                "PressContact": "christina.blakeman@wno.org.uk",
                "DateBkd": "15/03/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A56:H56": {
                "Day": "",
                "Date": "15/06/2024",
                "P": "",
                "Venue": "Sadler's Wells - Lilian Baylis Studio (6pm)",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Florencia Oz, En este dia en este mundo",
                "ShowIsTitleTba": "",
                "Producer": "Sadler's Wells",
                "PressContact": "andrea.gillespie@sadlerswells.com",
                "DateBkd": 45419,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A57:H57": {
                "Day": "",
                "Date": "15/06/2024",
                "P": "",
                "Venue": "Sadler's Wells - Lilian Baylis Studio (6pm)",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Maria Jose Llergo, ULTRABELLEZA",
                "ShowIsTitleTba": "",
                "Producer": "Sadler's Wells",
                "PressContact": "andrea.gillespie@sadlerswells.com",
                "DateBkd": 45419,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "16/06/2024": {
            "A58:H58": {
                "Day": "Sunday",
                "Date": "16/06/2024",
                "P": "",
                "Venue": "",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "",
                "ShowIsTitleTba": "",
                "Producer": "",
                "PressContact": "",
                "DateBkd": "",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A59:H59": {
                "Day": "Monday",
                "Date": "16/06/2024",
                "P": "",
                "Venue": "TBA",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "TBA",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "kate@katemorleypr.com",
                "DateBkd": "18/10/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "17/06/2024": {
            "A60:H60": {
                "Day": "",
                "Date": "17/06/2024",
                "P": "",
                "Venue": "Jerwood Theatre Upstairs",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Bounds ",
                "ShowIsTitleTba": "",
                "Producer": "Royal Court",
                "PressContact": "EllaGold@royalcourttheatre.com",
                "DateBkd": "16/02/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A61:H61": {
                "Day": "",
                "Date": "17/06/2024",
                "P": "",
                "Venue": "Leeds Playhouse",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Here You Come Again",
                "ShowIsTitleTba": "",
                "Producer": "Leeds Playhouse & Simon Friend",
                "PressContact": "Rachel.marriner@leedsplayhouse.org.uk/07729 206332 \n",
                "DateBkd": 45400,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "18/06/2024": {
            "A62:H62": {
                "Day": "",
                "Date": "18/06/2024",
                "P": "",
                "Venue": "Dominion Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Sister Act - Gala night",
                "ShowIsTitleTba": "",
                "Producer": "JWP",
                "PressContact": "daniel@rawpr.co.uk/020 3829 0930",
                "DateBkd": 45425,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A63:H63": {
                "Day": "Tuesday",
                "Date": "18/06/2024",
                "P": "",
                "Venue": "Sadler's Wells",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Marlene Monteiro Freitas’s Bacchae: Prelude to a Purge ",
                "ShowIsTitleTba": "",
                "Producer": "LIFT and Sadler’s Wells ",
                "PressContact": "kate@breadandbutterpr.uk, ben@breadandbutterpr.uk",
                "DateBkd": 45118,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A64:H64": {
                "Day": "",
                "Date": "18/06/2024",
                "P": "",
                "Venue": "Barbican Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Kiss me Kate",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "hannah@neilreadingpr.com",
                "DateBkd": 45119,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A65:H65": {
                "Day": "",
                "Date": "18/06/2024",
                "P": "",
                "Venue": "Globe Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Taming of the Shrew",
                "ShowIsTitleTba": "",
                "Producer": "Shakespeare's Globe",
                "PressContact": "alice.r@shakespearesglobe.com",
                "DateBkd": "23/01/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A66:H66": {
                "Day": "",
                "Date": "18/06/2024",
                "P": "",
                "Venue": "Almeida Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Alma Mater",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "zinnes@almeida.co.uk",
                "DateBkd": 45536,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A67:H67": {
                "Day": "",
                "Date": "18/06/2024",
                "P": "",
                "Venue": "Garrick Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Boys From the Blackstuff - GALA NIGHT",
                "ShowIsTitleTba": "",
                "Producer": "Bill Kenwright Ltd",
                "PressContact": "Amanda Malpass, 07554 424256, amanda@amandamalpass.com",
                "DateBkd": 45412,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "19/06/2024": {
            "A68:H68": {
                "Day": "Wednesday",
                "Date": "19/06/2024",
                "P": "",
                "Venue": "",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "",
                "ShowIsTitleTba": "",
                "Producer": "",
                "PressContact": "",
                "DateBkd": "",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "20/06/2024": {
            "A69:H69": {
                "Day": "Thursday",
                "Date": "20/06/2024",
                "P": "P",
                "Venue": "TBA",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "TBA",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "chloe@aboutgracepr.com",
                "DateBkd": "27/09/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A70:H70": {
                "Day": "",
                "Date": "20/06/2024",
                "P": "",
                "Venue": "The Coronet Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Beckett Trilogy",
                "ShowIsTitleTba": "",
                "Producer": "Gare St Lazare Ireland",
                "PressContact": "sharon@keanlanyon.com  07973 843133",
                "DateBkd": 45326,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A71:H71": {
                "Day": "",
                "Date": "20/06/2024",
                "P": "",
                "Venue": "East London Shakespeare Festival",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Much Ado About Nothing",
                "ShowIsTitleTba": "",
                "Producer": "East London Shakespeare Festival",
                "PressContact": "caroline@capr.co.uk, 07748 603841",
                "DateBkd": 45405,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A72:H72": {
                "Day": "",
                "Date": "20/06/2024",
                "P": "",
                "Venue": "Soho Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "House of Life",
                "ShowIsTitleTba": "",
                "Producer": "Sam Hodges",
                "PressContact": "chloe@aboutgracepr.com, 07725619711",
                "DateBkd": 45415,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "21/06/2024": {
            "A73:H73": {
                "Day": "Friday",
                "Date": "21/06/2024",
                "P": "",
                "Venue": "Sadler's Wells",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Acrobatic Swan Lake",
                "ShowIsTitleTba": "",
                "Producer": "Joyway London",
                "PressContact": "katherine@brightmediauk.com /  07958 649502",
                "DateBkd": "16/01/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A74:H74": {
                "Day": "",
                "Date": "21/06/2024",
                "P": "",
                "Venue": "TBA",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "TBA",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "KatieMD@katemorleypr.com",
                "DateBkd": "20/02/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A75:H75": {
                "Day": "",
                "Date": "21/06/2024",
                "P": "",
                "Venue": "Peterborough New Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Rent",
                "ShowIsTitleTba": "",
                "Producer": "Landmark Theatre",
                "PressContact": "becky@bmpr.co.uk",
                "DateBkd": "22/03/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A76:H76": {
                "Day": "",
                "Date": "21/06/2024",
                "P": "",
                "Venue": "Bush Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "My Father’s Fable",
                "ShowIsTitleTba": "",
                "Producer": "Bush Theatre",
                "PressContact": "Martin Shippen / shippen.martin@gmail.com / 07956 879165",
                "DateBkd": 45413,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A77:H77": {
                "Day": "Saturday",
                "Date": "21/06/2024",
                "P": "",
                "Venue": "The Old Bailey",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "LIFT Festival: L'Animale",
                "ShowIsTitleTba": "",
                "Producer": "LIFT",
                "PressContact": "ben@breadandbutterpr.uk",
                "DateBkd": "22/03/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "23/06/2024": {
            "A78:H78": {
                "Day": "Sunday",
                "Date": "23/06/2024",
                "P": "",
                "Venue": "GLYNDEBOURNE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Giulio Cesare",
                "ShowIsTitleTba": "",
                "Producer": "Glyndebourne Productions Ltd",
                "PressContact": "kate.harvey@glyndebourne.com, 01273 102 307",
                "DateBkd": "22/08/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A79:H79": {
                "Day": "",
                "Date": "23/06/2024",
                "P": "",
                "Venue": "SADLER'S WELLS",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Nadiya and Kai: Behind the Magic ",
                "ShowIsTitleTba": "",
                "Producer": "Senbla Ltd",
                "PressContact": "info@planetearthpublicity.com",
                "DateBkd": 45118,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "24/06/2024": {
            "A80:H80": {
                "Day": "Monday",
                "Date": "24/06/2024",
                "P": "",
                "Venue": "Brixton House",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Everything I Own",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "monique.baptiste-brown@brixtonhouse.co.uk",
                "DateBkd": "27/11/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A81:H81": {
                "Day": "",
                "Date": "24/06/2024",
                "P": "",
                "Venue": "Park Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "\nThe Marilyn Conspiracy \n",
                "ShowIsTitleTba": "",
                "Producer": "\nGuy Masterson – Theatre Tours International Ltd and Park Theatre\n",
                "PressContact": "emma@mobiusindustries.com",
                "DateBkd": 45180,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A82:H82": {
                "Day": "",
                "Date": "24/06/2024",
                "P": "",
                "Venue": "TBA",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "TBA",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "katiemd@katemorleypr.com",
                "DateBkd": "20/02/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "25/06/2024": {
            "A83:H83": {
                "Day": "Tuesday",
                "Date": "25/06/2024",
                "P": "",
                "Venue": "Swan Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Kyoto",
                "ShowIsTitleTba": "",
                "Producer": "RSC",
                "PressContact": "dean.asker@rsc.org.uk ",
                "DateBkd": "25/09/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A84:H84": {
                "Day": "",
                "Date": "25/06/2024",
                "P": "",
                "Venue": "REGENT'S PARK OPEN AIR THEATRE (7.45pm)",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Secret Garden",
                "ShowIsTitleTba": "",
                "Producer": "Regent's Park Open Air Theatre",
                "PressContact": "tom@joallanpr.com",
                "DateBkd": "26/09/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A85:H85": {
                "Day": "",
                "Date": "25/06/2024",
                "P": "",
                "Venue": "The Old Vic",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "the Constituent",
                "ShowIsTitleTba": "",
                "Producer": "The Old Vic",
                "PressContact": "katie.marsh@oldvictheatre.com ",
                "DateBkd": 45629,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A95:H95": {
                "Day": "Tuesday",
                "Date": "25/06/2024",
                "P": "N/A",
                "Venue": "WATERMILL",
                "OtherVenue": "N/A",
                "VenueIsTba": "N/A",
                "TitleOfShow": "Test",
                "ShowIsTitleTba": "N/A",
                "Producer": "Producer",
                "PressContact": "test@test.co.uk",
                "DateBkd": "N/A",
                "UserId": "N/A",
                "IsSeasonGala": "N/A",
                "IsOperaDance": "N/A"
            },
            "A96:H96": {
                "Day": "Tuesday",
                "Date": "25/06/2024",
                "P": "P",
                "Venue": "N/A",
                "OtherVenue": "N/A",
                "VenueIsTba": "TBA",
                "TitleOfShow": "N/A",
                "ShowIsTitleTba": "TBA",
                "Producer": "Producer",
                "PressContact": "test@test.co.uk",
                "DateBkd": "N/A",
                "UserId": "N/A",
                "IsSeasonGala": "Season Gala",
                "IsOperaDance": "N/A"
            }
        },
        "26/06/2024": {
            "A86:H86": {
                "Day": "Wednesday",
                "Date": "26/06/2024",
                "P": "",
                "Venue": "ROYAL OPERA HOUSE MAIN STAGE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Così fan tutte",
                "ShowIsTitleTba": "",
                "Producer": "The Royal Opera",
                "PressContact": "Chloe.Westwood@roh.org.uk",
                "DateBkd": "21/06/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A87:H87": {
                "Day": "",
                "Date": "26/06/2024",
                "P": "",
                "Venue": "PITLOCHRY FESTIVAL THEATRE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Sense And Sensibility",
                "ShowIsTitleTba": "",
                "Producer": "Pitlochry Festival Theatre",
                "PressContact": "duncanclarkepr@gmail.com / 0788093750",
                "DateBkd": "25/09/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A88:H88": {
                "Day": "",
                "Date": "26/06/2024",
                "P": "",
                "Venue": "Wyndham’s Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Next To Normal",
                "ShowIsTitleTba": "",
                "Producer": "Playful Productions",
                "PressContact": "david.bloom@storyhousepr.co.uk",
                "DateBkd": "17/10/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A89:H89": {
                "Day": "",
                "Date": "26/06/2024",
                "P": "",
                "Venue": "SAVOY THEATRE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Mean Girls",
                "ShowIsTitleTba": "",
                "Producer": "Lorne Michaels, Sonia Friedman Productions, and David Ian for Crossroads Live",
                "PressContact": "rozzie.inge@dawbell.com & esther.beaumont@dawbell.com",
                "DateBkd": "25/03/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A97:H97": {
                "Day": "Wednesday",
                "Date": "26/06/2024",
                "P": "N/A",
                "Venue": "Omnibus Theatre (Part of 96 Festival)",
                "OtherVenue": "N/A",
                "VenueIsTba": "N/A",
                "TitleOfShow": "GEORGE (TEST)",
                "ShowIsTitleTba": "N/A",
                "Producer": "MQT Productions in association with Exchange Theatre",
                "PressContact": "annabelle@mobiusindustries.com",
                "DateBkd": "N/A",
                "UserId": "N/A",
                "IsSeasonGala": "N/A",
                "IsOperaDance": "N/A"
            }
        },
        "27/06/2024": {
            "A90:H90": {
                "Day": "Thursday",
                "Date": "27/06/2024",
                "P": "",
                "Venue": "Omnibus Theatre (Part of 96 Festival)",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "GEORGE",
                "ShowIsTitleTba": "",
                "Producer": "MQT Productions in association with Exchange Theatre",
                "PressContact": "annabelle@mobiusindustries.com",
                "DateBkd": 45419,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "28/06/2024": {
            "A91:H91": {
                "Day": "",
                "Date": "28/06/2024",
                "P": "",
                "Venue": "",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "",
                "ShowIsTitleTba": "",
                "Producer": "",
                "PressContact": "",
                "DateBkd": "",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A92:H92": {
                "Day": "Friday",
                "Date": "28/06/2024",
                "P": "",
                "Venue": "",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "",
                "ShowIsTitleTba": "",
                "Producer": "",
                "PressContact": "",
                "DateBkd": "",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "29/06/2024": {
            "A93:H93": {
                "Day": "Saturday",
                "Date": "29/06/2024",
                "P": "",
                "Venue": "Polka Theatre ",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Sam Wu is NOT Afraid of Ghosts",
                "ShowIsTitleTba": "",
                "Producer": "Polka Theatre ",
                "PressContact": "arabella@anrpr.co.uk ",
                "DateBkd": "13/12/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "30/06/2024": {
            "A94:H94": {
                "Day": "Sunday",
                "Date": "30/06/2024",
                "P": "",
                "Venue": "TROUBADOUR WEMBLEY PARK THEATRE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Starlight Express",
                "ShowIsTitleTba": "",
                "Producer": "Lloyd Webber Harrison Musicals",
                "PressContact": "david.bloom@storyhousepr.co.uk",
                "DateBkd": 45239,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "01/07/2024": {
            "A98:H98": {
                "Day": "",
                "Date": "01/07/2024",
                "P": "",
                "Venue": "ROYAL OPERA HOUSE MAIN STAGE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Tosca",
                "ShowIsTitleTba": "",
                "Producer": "The Royal Opera",
                "PressContact": "Chloe.Westwood@roh.org.uk",
                "DateBkd": "21/06/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A99:H99": {
                "Day": "",
                "Date": "01/07/2024",
                "P": "",
                "Venue": "HAMPSTEAD THEATRE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Visit from an Unknown Woman ",
                "ShowIsTitleTba": "",
                "Producer": "Hampstead Theatre",
                "PressContact": "clarejh@hampsteadtheatre.com",
                "DateBkd": "20/10/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "02/07/2024": {
            "A100:H100": {
                "Day": "",
                "Date": "02/07/2024",
                "P": "",
                "Venue": "SADLER'S WELLS",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Carlos Acosta’s Carmen  ",
                "ShowIsTitleTba": "",
                "Producer": "Acosta Danza ",
                "PressContact": "lucy.colomb@sadlerswells.com   ",
                "DateBkd": 45204,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "2/07/2024": {
            "A101:H101": {
                "Day": "",
                "Date": "2/07/2024",
                "P": "",
                "Venue": "NATIONAL THEATRE - Olivier",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Mnemonic",
                "ShowIsTitleTba": "",
                "Producer": "National Theatre",
                "PressContact": "press@nationaltheatre.org.uk",
                "DateBkd": "21/07/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "03/07/2024": {
            "A102:H102": {
                "Day": "",
                "Date": "03/07/2024",
                "P": "",
                "Venue": "Southwark Playhouse",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "TBA",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "katiemd@katemorleypr.com",
                "DateBkd": "20/02/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "04/07/2024": {
            "A103:H103": {
                "Day": "",
                "Date": "04/07/2024",
                "P": "",
                "Venue": "DONMAR WAREHOUSE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "PRIMARY TRUST",
                "ShowIsTitleTba": "",
                "Producer": "Donmar Warehouse",
                "PressContact": "kate@katemorleypr.com",
                "DateBkd": "22/09/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "05/07/2024": {
            "A104:H104": {
                "Day": "",
                "Date": "05/07/2024",
                "P": "",
                "Venue": "SOUTHWARK PLAYHOUSE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "TBA",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "julia@katemorleypr.com",
                "DateBkd": 44968,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A105:H105": {
                "Day": "",
                "Date": "05/07/2024",
                "P": "",
                "Venue": "Harold Pinter Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Your Lie In April [12-week season not one-nighter]",
                "ShowIsTitleTba": "",
                "Producer": "Carter Dixon McGill Ltd, Indie Theatrical, Pinnacle Productions, Scott Prisand, Sophie Qi \n",
                "PressContact": "kevinwilsonpr@gmail.com, 07884 368697",
                "DateBkd": 45405,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "06/07/2024": {
            "A106:H106": {
                "Day": "",
                "Date": "06/07/2024",
                "P": "",
                "Venue": "Polka Theatre ",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "How to Catch A Star, ",
                "ShowIsTitleTba": "",
                "Producer": "Branar ",
                "PressContact": "arabella@anrpr.co.uk ",
                "DateBkd": "13/12/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "07/07/2024": {
            "A107:H107": {
                "Day": "",
                "Date": "07/07/2024",
                "P": "",
                "Venue": "",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "",
                "ShowIsTitleTba": "",
                "Producer": "",
                "PressContact": "",
                "DateBkd": "",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "08/07/2024": {
            "A108:H108": {
                "Day": "",
                "Date": "08/07/2024",
                "P": "",
                "Venue": "Curve ",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "A Chorus Line",
                "ShowIsTitleTba": "",
                "Producer": "Curve",
                "PressContact": "f.moore@curvetheatre.co.uk / 07808 304633",
                "DateBkd": 45394,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "09/07/2024": {
            "A109:H109": {
                "Day": "",
                "Date": "09/07/2024",
                "P": "",
                "Venue": "Royal Shakespeare Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The School For Scandal",
                "ShowIsTitleTba": "",
                "Producer": "RSC",
                "PressContact": "dean.asker@rsc.org.uk ",
                "DateBkd": 45240,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A110:H110": {
                "Day": "",
                "Date": "09/07/2024",
                "P": "",
                "Venue": "Bindweed",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Arcola Theatre",
                "ShowIsTitleTba": "",
                "Producer": "HighTide at Arcola Theatre",
                "PressContact": "katiemd@katemorleypr.com",
                "DateBkd": 45505,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A111:H111": {
                "Day": "",
                "Date": "09/07/2024",
                "P": "",
                "Venue": "The Watermill",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Barnum",
                "ShowIsTitleTba": "",
                "Producer": "The Watermill",
                "PressContact": "Arabella@anrpr.co.uk",
                "DateBkd": 45537,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A112:H112": {
                "Day": "",
                "Date": "09/07/2024",
                "P": "",
                "Venue": "Southwark Playhouse Elephant",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Children's Inquiry",
                "ShowIsTitleTba": "",
                "Producer": "LUNG",
                "PressContact": "elaine@mobiusindustries.com and 07904334809",
                "DateBkd": 45405,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "10/07/2024": {
            "A113:H113": {
                "Day": "",
                "Date": "10/07/2024",
                "P": "",
                "Venue": "PITLOCHRY FESTIVAL THEATRE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Shirley Valentine",
                "ShowIsTitleTba": "",
                "Producer": "Pitlochry Festival Theatre",
                "PressContact": "duncanclarkepr@gmail.com / 0788093750",
                "DateBkd": "25/09/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A114:H114": {
                "Day": "",
                "Date": "10/07/2024",
                "P": "",
                "Venue": "Noel Coward Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Slave Play",
                "ShowIsTitleTba": "",
                "Producer": "Empire Street Productions",
                "PressContact": "laura@aboutgracepr.com chloe@aboutgracepr.com ",
                "DateBkd": "18/12/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A115:H115": {
                "Day": "",
                "Date": "10/07/2024",
                "P": "",
                "Venue": "Southwark Playhouse",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "DORIAN: The Musical",
                "ShowIsTitleTba": "",
                "Producer": "Southwark Playhouse",
                "PressContact": "Madelaine@gingerBreadagency.com, Rosiemai@GingerBreadagency.com",
                "DateBkd": 45042,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "11/07/2024": {
            "A116:H116": {
                "Day": "",
                "Date": "11/07/2024",
                "P": "",
                "Venue": "The Roundhouse",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Fuerza Bruta",
                "ShowIsTitleTba": "",
                "Producer": "The Roundhouse, Kindred Spirits and Fuerza Bruta",
                "PressContact": "chloe@breadandbutterpr.uk",
                "DateBkd": "14/11/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A117:H117": {
                "Day": "",
                "Date": "11/07/2024",
                "P": "",
                "Venue": "Crucible Theatre, Sheffield",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Chariots of Fire",
                "ShowIsTitleTba": "",
                "Producer": "Sheffield Theatres",
                "PressContact": "flavia@joallanpr.com",
                "DateBkd": "17/01/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A118:H118": {
                "Day": "",
                "Date": "11/07/2024",
                "P": "",
                "Venue": "Harold Pinter Theatre",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Blippi: The Wonderful World Tour 10.30am and 1pm",
                "ShowIsTitleTba": "",
                "Producer": "Round Room Live",
                "PressContact": "tommy@tommyluck.co.uk",
                "DateBkd": 45414,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A119:H119": {
                "Day": "",
                "Date": "11/07/2024",
                "P": "",
                "Venue": "Barn Theatre, Cirencester",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Some Mothers Do Have 'Em",
                "ShowIsTitleTba": "",
                "Producer": "Barn Theatre",
                "PressContact": "Arabella@anrpr.co.uk",
                "DateBkd": 45419,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "12/07/2024": {
            "A120:H120": {
                "Day": "",
                "Date": "12/07/2024",
                "P": "",
                "Venue": "ROYAL OPERA HOUSE MAIN STAGE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Madama Butterfly",
                "ShowIsTitleTba": "",
                "Producer": "The Royal Opera",
                "PressContact": "Chloe.Westwood@roh.org.uk",
                "DateBkd": "21/06/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A121:H121": {
                "Day": "",
                "Date": "12/07/2024",
                "P": "",
                "Venue": "Leeds Playhouse",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Paranormal Activity",
                "ShowIsTitleTba": "",
                "Producer": "Leeds Playhouse",
                "PressContact": "Rachel.marriner@leedsplayhouse.org.uk/07729 206332 \n",
                "DateBkd": 45400,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "13/07/2024": {
            "A122:H122": {
                "Day": "",
                "Date": "13/07/2024",
                "P": "",
                "Venue": "PITLOCHRY FESTIVAL THEATRE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Secret Garden",
                "ShowIsTitleTba": "",
                "Producer": "Pitlochry Festival Theatre",
                "PressContact": "duncanclarkepr@gmail.com / 0788093750",
                "DateBkd": "25/09/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A123:H123": {
                "Day": "",
                "Date": "13/07/2024",
                "P": "",
                "Venue": "London County Hall",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Paddington Bear Experience",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "laura@aboutgracepr.com",
                "DateBkd": 45429,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "14/07/2024": {
            "A124:H124": {
                "Day": "",
                "Date": "14/07/2024",
                "P": "",
                "Venue": "The Mill at Sonning ",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "3 Men in a Boat",
                "ShowIsTitleTba": "",
                "Producer": "The Mill at Sonning ",
                "PressContact": "kevinwilsonpr@gmail.com",
                "DateBkd": "27/11/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A125:H125": {
                "Day": "",
                "Date": "14/07/2024",
                "P": "",
                "Venue": "London County Hall",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Paddington Bear Experience",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "laura@aboutgracepr.com",
                "DateBkd": 45429,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "15/07/2024": {
            "A126:H126": {
                "Day": "",
                "Date": "15/07/2024",
                "P": "",
                "Venue": "The Mill at Sonning ",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "3 Men in a Boat",
                "ShowIsTitleTba": "",
                "Producer": "The Mill at Sonning ",
                "PressContact": "kevinwilsonpr@gmail.com",
                "DateBkd": "27/11/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A127:H127": {
                "Day": "",
                "Date": "15/07/2024",
                "P": "",
                "Venue": "London County Hall",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Paddington Bear Experience",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "laura@aboutgracepr.com",
                "DateBkd": 45429,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "16/07/2024": {
            "A128:H128": {
                "Day": "",
                "Date": "16/07/2024",
                "P": "",
                "Venue": "",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "",
                "ShowIsTitleTba": "",
                "Producer": "",
                "PressContact": "",
                "DateBkd": "",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "17/07/2024": {
            "A129:H129": {
                "Day": "",
                "Date": "17/07/2024",
                "P": "",
                "Venue": "Jerwood Theatre Downstairs",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "ECHO (Every Cold Hearted Oxygen)  ",
                "ShowIsTitleTba": "",
                "Producer": "Royal Court",
                "PressContact": "ellagold@royalcourttheatre.com",
                "DateBkd": "19/01/2024",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A130:H130": {
                "Day": "",
                "Date": "17/07/2024",
                "P": "",
                "Venue": "Brixton House",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Before I go",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "press@brixtonhouse.co.uk",
                "DateBkd": "25/03/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A131:H131": {
                "Day": "",
                "Date": "17/07/2024",
                "P": "",
                "Venue": "Menier Chocolate Factory",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Baker’s Wife",
                "ShowIsTitleTba": "",
                "Producer": "Menier Chocolate Factory",
                "PressContact": "kate@katemorleypr.com",
                "DateBkd": 45407,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "18/07/2024": {
            "A132:H132": {
                "Day": "",
                "Date": "18/07/2024",
                "P": "",
                "Venue": "National Theatre - Dorfman",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Hot Wing King",
                "ShowIsTitleTba": "",
                "Producer": "National Theatre",
                "PressContact": "press@nationaltheatre.org.uk",
                "DateBkd": "23/06/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A133:H133": {
                "Day": "",
                "Date": "18/07/2024",
                "P": "",
                "Venue": "THE LONDON PALLADIUM",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Hello, Dolly!",
                "ShowIsTitleTba": "",
                "Producer": "Michael Harrison",
                "PressContact": "david.bloom@storyhousepr.co.uk",
                "DateBkd": "13/12/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A134:H134": {
                "Day": "",
                "Date": "18/07/2024",
                "P": "",
                "Venue": "ORANGE TREE THEATRE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Red Speedo",
                "ShowIsTitleTba": "",
                "Producer": "Orange Tree Theatre",
                "PressContact": "katiemd@katemorleypr.com",
                "DateBkd": 45056,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A135:H135": {
                "Day": "",
                "Date": "18/07/2024",
                "P": "",
                "Venue": "Theatre Royal Bath",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Mixed Bill",
                "ShowIsTitleTba": "",
                "Producer": "London City Ballet",
                "PressContact": "skye@breadandbutterpr.uk",
                "DateBkd": 45506,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A136:H136": {
                "Day": "",
                "Date": "18/07/2024",
                "P": "",
                "Venue": "Southbank Centre's Queen Elizabeth Hall",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Crazy Smooth: In My Body",
                "ShowIsTitleTba": "",
                "Producer": "TBA",
                "PressContact": "louise.gilbert@southbankcentre.co.uk",
                "DateBkd": 45537,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "19/07/2024": {
            "A137:H137": {
                "Day": "",
                "Date": "19/07/2024",
                "P": "",
                "Venue": "",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "",
                "ShowIsTitleTba": "",
                "Producer": "",
                "PressContact": "",
                "DateBkd": "",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "20/07/2024": {
            "A138:H138": {
                "Day": "",
                "Date": "20/07/2024",
                "P": "",
                "Venue": "ROYAL OPERA HOUSE MAIN STAGE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Jette Parker Artists Summer Performance",
                "ShowIsTitleTba": "",
                "Producer": "The Royal Opera",
                "PressContact": "Chloe.Westwood@roh.org.uk",
                "DateBkd": "21/06/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A139:H139": {
                "Day": "",
                "Date": "20/07/2024",
                "P": "",
                "Venue": "Lyric Theatre Shaftesbury Avenue",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Gruffalo",
                "ShowIsTitleTba": "",
                "Producer": "Tall Stories",
                "PressContact": "molly@aboutgracepr.com",
                "DateBkd": 45429,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "21/07/2024": {
            "A140:H140": {
                "Day": "",
                "Date": "21/07/2024",
                "P": "",
                "Venue": "Lyric Theatre Shaftesbury Avenue",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Gruffalo",
                "ShowIsTitleTba": "",
                "Producer": "Tall Stories",
                "PressContact": "molly@aboutgracepr.com",
                "DateBkd": 45429,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "22/07/2024": {
            "A141:H141": {
                "Day": "",
                "Date": "22/07/2024",
                "P": "",
                "Venue": "",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "",
                "ShowIsTitleTba": "",
                "Producer": "",
                "PressContact": "",
                "DateBkd": "",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "23/07/2024": {
            "A142:H142": {
                "Day": "",
                "Date": "23/07/2024",
                "P": "",
                "Venue": "LYRIC HAMMERSMITH THEATRE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "FANGIRLS",
                "ShowIsTitleTba": "",
                "Producer": "Lyric Hammersmith Theatre and Sonia Friedman Productions",
                "PressContact": "burte.tsogbadrakh@lyric.co.uk",
                "DateBkd": 45239,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "24/07/2024": {
            "A143:H143": {
                "Day": "",
                "Date": "24/07/2024",
                "P": "",
                "Venue": "The Holloway Garden Theatre (5pm)",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "As You Like It",
                "ShowIsTitleTba": "",
                "Producer": "RSC",
                "PressContact": "dean.asker@rsc.org.uk ",
                "DateBkd": "18/12/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A144:H144": {
                "Day": "",
                "Date": "24/07/2024",
                "P": "",
                "Venue": "Chichester Festival Theatre   ",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Oliver!",
                "ShowIsTitleTba": "",
                "Producer": "Chichester Festival Theatre",
                "PressContact": "lucinda.morrison@cft.org.uk",
                "DateBkd": "20/10/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "25/07/2024": {
            "A145:H145": {
                "Day": "",
                "Date": "25/07/2024",
                "P": "",
                "Venue": "NATIONAL THEATRE - Lyttleton",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Grapes Of Wrath",
                "ShowIsTitleTba": "",
                "Producer": "National Theatre",
                "PressContact": "press@nationaltheatre.org.uk",
                "DateBkd": "30/10/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            },
            "A146:H146": {
                "Day": "",
                "Date": "25/07/2024",
                "P": "",
                "Venue": "The Other Palace",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Fantastically Great Women Who Changed the World",
                "ShowIsTitleTba": "",
                "Producer": "Kenny Wax",
                "PressContact": "isobel@chloenelkinconsulting.com / 020 3627 2960",
                "DateBkd": 45413,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "26/07/2024": {
            "A147:H147": {
                "Day": "",
                "Date": "26/07/2024",
                "P": "",
                "Venue": "Eventim Apollo",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "Shrek The Musical",
                "ShowIsTitleTba": "",
                "Producer": "Mark Goucher, Matthew Gale and Gavin Kalin",
                "PressContact": "molly@aboutgracepr.com",
                "DateBkd": 45429,
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "27/07/2024": {
            "A148:H148": {
                "Day": "",
                "Date": "27/07/2024",
                "P": "",
                "Venue": "",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "",
                "ShowIsTitleTba": "",
                "Producer": "",
                "PressContact": "",
                "DateBkd": "",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "28/07/2024": {
            "A149:H149": {
                "Day": "",
                "Date": "28/07/2024",
                "P": "",
                "Venue": "",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "",
                "ShowIsTitleTba": "",
                "Producer": "",
                "PressContact": "",
                "DateBkd": "",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        },
        "29/07/2024": {
            "A150:H150": {
                "Day": "",
                "Date": "29/07/2024",
                "P": "",
                "Venue": "CHICHESTER MINERVA THEATRE",
                "OtherVenue": "",
                "VenueIsTba": "",
                "TitleOfShow": "The Promise",
                "ShowIsTitleTba": "",
                "Producer": "Chichester Festival Theatre",
                "PressContact": "lucinda.morrison@cft.org.uk",
                "DateBkd": "20/10/2023",
                "UserId": "",
                "IsSeasonGala": "",
                "IsOperaDance": ""
            }
        }
    }
}

export default testData;