const UKTVenues = [
    { value: "Aylesbury Waterside Theatre", label: "Aylesbury Waterside Theatre" },
    { value: "Belgrade Theatre", label: "Belgrade Theatre" },
    { value: "Birmingham Hippodrome", label: "Birmingham Hippodrome" },
    { value: "Birmingham Repertory Theatre", label: "Birmingham Repertory Theatre" },
    { value: "Birmingham Royal Ballet", label: "Birmingham Royal Ballet" },
    { value: "Bradford Theatres", label: "Bradford Theatres" },
    { value: "Bristol Hippodrome", label: "Bristol Hippodrome" },
    { value: "Bristol Old Vic", label: "Bristol Old Vic" },
    { value: "British Youth Music Theatre", label: "British Youth Music Theatre" },
    { value: "Brixton House", label: "Brixton House" },
    { value: "Brunton Theatre", label: "Brunton Theatre" },
    {
        value: "Buxton Opera House and Pavilion Arts Centre",
        label: "Buxton Opera House and Pavilion Arts Centre",
    },
    { value: "Capital Theatres", label: "Capital Theatres" },
    { value: "Cheek by Jowl", label: "Cheek by Jowl" },
    { value: "Chichester Festival Theatre", label: "Chichester Festival Theatre" },
    { value: "Chipping Norton Theatre", label: "Chipping Norton Theatre" },
    { value: "Churchill Theatre", label: "Churchill Theatre" },
    { value: "Citizens Theatre", label: "Citizens Theatre" },
    { value: "Cockpit Theatre", label: "Cockpit Theatre" },
    { value: "Complicite", label: "Complicite" },
    { value: "Curve Theatre", label: "Curve Theatre" },
    { value: "Dance Consortium Ltd", label: "Dance Consortium Ltd" },
    { value: "Darlington Hippodrome", label: "Darlington Hippodrome" },
    { value: "Derby Theatre", label: "Derby Theatre" },
    { value: "Devonshire Park Theatre", label: "Devonshire Park Theatre" },
    { value: "D'Oyly Carte Opera Company", label: "D'Oyly Carte Opera Company" },
    { value: "Dundee Repertory Theatre", label: "Dundee Repertory Theatre" },
    { value: "Eclipse Theatre Company", label: "Eclipse Theatre Company" },
    { value: "Edinburgh Playhouse", label: "Edinburgh Playhouse" },
    { value: "English National Ballet", label: "English National Ballet" },
    { value: "English National Opera", label: "English National Opera" },
    { value: "English Touring Theatre", label: "English Touring Theatre" },
    { value: "Everyman Theatre", label: "Everyman Theatre" },
    { value: "Exeter Northcott Theatre Company", label: "Exeter Northcott Theatre Company" },
    { value: "G Live Guildford", label: "G Live Guildford" },
    { value: "Glyndebourne", label: "Glyndebourne" },
    { value: "Graeae Theatre Company", label: "Graeae Theatre Company" },
    { value: "Grand Opera House Belfast", label: "Grand Opera House Belfast" },
    { value: "Grand Opera House York", label: "Grand Opera House York" },
    { value: "Grand Theatre Blackpool", label: "Grand Theatre Blackpool" },
    { value: "Hall for Cornwall", label: "Hall for Cornwall" },
    { value: "Harrogate Theatre", label: "Harrogate Theatre" },
    { value: "Headlong Theatre Ltd", label: "Headlong Theatre Ltd" },
    { value: "Hertford Theatre", label: "Hertford Theatre" },
    { value: "HOME", label: "HOME" },
    { value: "Hull New Theatre", label: "Hull New Theatre" },
    { value: "Hull Truck Theatre", label: "Hull Truck Theatre" },
    { value: "Imitating The Dog Limited", label: "Imitating The Dog Limited" },
    { value: "Interplay Theatre", label: "Interplay Theatre" },
    { value: "Key Theatre", label: "Key Theatre" },
    { value: "King's Theatre Glasgow", label: "King's Theatre Glasgow" },
    { value: "Landmark Theatres Limited", label: "Landmark Theatres Limited" },
    { value: "Leas Cliff Hall", label: "Leas Cliff Hall" },
    { value: "Leeds Heritage Theatres", label: "Leeds Heritage Theatres" },
    { value: "Leeds Playhouse", label: "Leeds Playhouse" },
    { value: "Lilian Baylis Studio Sadlers Wells", label: "Lilian Baylis Studio Sadlers Wells" },
    {
        value: "Liverpool & Merseyside Theatres Trust Ltd",
        label: "Liverpool & Merseyside Theatres Trust Ltd",
    },
    { value: "Liverpool Empire", label: "Liverpool Empire" },
    { value: "Lyceum Theatre Crewe", label: "Lyceum Theatre Crewe" },
    { value: "Lyric Theatre Belfast", label: "Lyric Theatre Belfast" },
    { value: "Malvern Theatres", label: "Malvern Theatres" },
    { value: "Marina Theatre", label: "Marina Theatre" },
    { value: "Marlowe Theatre", label: "Marlowe Theatre" },
    { value: "MAST Mayflower Studios", label: "MAST Mayflower Studios" },
    { value: "Mayflower Theatre", label: "Mayflower Theatre" },
    { value: "Mercury Theatre", label: "Mercury Theatre" },
    { value: "Middlesbrough Theatre", label: "Middlesbrough Theatre" },
    { value: "Midland Arts Centre (MAC)", label: "Midland Arts Centre (MAC)" },
    { value: "Milton Keynes Theatre", label: "Milton Keynes Theatre" },
    { value: "National Theatre of Scotland", label: "National Theatre of Scotland" },
    { value: "New Theatre Cardiff", label: "New Theatre Cardiff" },
    { value: "New Theatre Oxford", label: "New Theatre Oxford" },
    { value: "New Theatre Peterborough", label: "New Theatre Peterborough" },
    { value: "New Vic Theatre", label: "New Vic Theatre" },
    { value: "New Victoria Theatre Woking", label: "New Victoria Theatre Woking" },
    { value: "New Wolsey Theatre Company", label: "New Wolsey Theatre Company" },
    { value: "Newcastle Theatre Royal", label: "Newcastle Theatre Royal" },
    { value: "Northern Ballet", label: "Northern Ballet" },
    { value: "Northern Broadsides", label: "Northern Broadsides" },
    { value: "Northern Stage", label: "Northern Stage" },
    { value: "Norwich Theatre Royal", label: "Norwich Theatre Royal" },
    { value: "Nottingham Playhouse", label: "Nottingham Playhouse" },
    { value: "Octagon Theatre", label: "Octagon Theatre" },
    { value: "Opera House Manchester", label: "Opera House Manchester" },
    { value: "Orchard Theatre Dartford Ltd", label: "Orchard Theatre Dartford Ltd" },
    { value: "Oxford Playhouse", label: "Oxford Playhouse" },
    { value: "Palace Theatre Manchester", label: "Palace Theatre Manchester" },
    { value: "Pegasus Theatre Trust", label: "Pegasus Theatre Trust" },
    { value: "Pilot Theatre Company", label: "Pilot Theatre Company" },
    { value: "Pitlochry Festival Theatre", label: "Pitlochry Festival Theatre" },
    { value: "Play to the Crowd", label: "Play to the Crowd" },
    { value: "Poole Arts Trust Ltd", label: "Poole Arts Trust Ltd" },
    { value: "Princess Theatre Torquay", label: "Princess Theatre Torquay" },
    { value: "Queen's Theatre Hornchurch", label: "Queen's Theatre Hornchurch" },
    { value: "Queen's Theatre Barnstaple", label: "Queen's Theatre Barnstaple" },
    { value: "Rambert", label: "Rambert" },
    { value: "Red Rose Chain", label: "Red Rose Chain" },
    { value: "Regent's Park Open Air Theatre", label: "Regent's Park Open Air Theatre" },
    { value: "Richmond Theatre", label: "Richmond Theatre" },
    { value: "Rifco Theatre Company", label: "Rifco Theatre Company" },
    { value: "Rose Theatre Kingston", label: "Rose Theatre Kingston" },
    { value: "Royal & Derngate Northampton", label: "Royal & Derngate Northampton" },
    {
        value: "Royal Court Theatre (Jerwood Theatre Upstairs)",
        label: "Royal Court Theatre (Jerwood Theatre Upstairs)",
    },
    { value: "Royal Exchange Theatre", label: "Royal Exchange Theatre" },
    { value: "Royal Lyceum Theatre Company", label: "Royal Lyceum Theatre Company" },
    { value: "Royal Opera House", label: "Royal Opera House" },
    { value: "Royal Shakespeare Company", label: "Royal Shakespeare Company" },
    { value: "Scottish Ballet", label: "Scottish Ballet" },
    { value: "Scottish Opera", label: "Scottish Opera" },
    { value: "Sheffield Theatres", label: "Sheffield Theatres" },
    { value: "Sherman Cymru", label: "Sherman Cymru" },
    { value: "Southend Theatres", label: "Southend Theatres" },
    { value: "Stephen Joseph Theatre", label: "Stephen Joseph Theatre" },
    { value: "Stockroom", label: "Stockroom" },
    { value: "Stockton Globe", label: "Stockton Globe" },
    { value: "Stoke-On-Trent Theatres", label: "Stoke-On-Trent Theatres" },
    { value: "Storyhouse", label: "Storyhouse" },
    { value: "Sunderland Empire", label: "Sunderland Empire" },
    { value: "Tangle", label: "Tangle" },
    { value: "Tara Theatre", label: "Tara Theatre" },
    { value: "The Alexandra Birmingham", label: "The Alexandra Birmingham" },
    { value: "The Beck Theatre Hayes", label: "The Beck Theatre Hayes" },
    { value: "The Capitol Horsham", label: "The Capitol Horsham" },
    { value: "The Landmark Ilfracombe", label: "The Landmark Ilfracombe" },
    { value: "The Mill at Sonning Theatre", label: "The Mill at Sonning Theatre" },
    { value: "The Minack Theatre Trust", label: "The Minack Theatre Trust" },
    {
        value: "The National Youth Theatre of Great Britain",
        label: "The National Youth Theatre of Great Britain",
    },
    { value: "The Riverfront Theatre", label: "The Riverfront Theatre" },
    { value: "The SandPit Theatre", label: "The SandPit Theatre" },
    { value: "The Woodville", label: "The Woodville" },
    { value: "Theatr Clwyd", label: "Theatr Clwyd" },
    { value: "Theatr Genedlaethol Cymru", label: "Theatr Genedlaethol Cymru" },
    { value: "Theatre by the Lake", label: "Theatre by the Lake" },
    { value: "Theatre Royal Bath", label: "Theatre Royal Bath" },
    { value: "Theatre Royal Brighton", label: "Theatre Royal Brighton" },
    { value: "Theatre Royal Bury St Edmunds", label: "Theatre Royal Bury St Edmunds" },
    { value: "Theatre Royal Plymouth", label: "Theatre Royal Plymouth" },
    { value: "Theatre Royal Windsor", label: "Theatre Royal Windsor" },
    { value: "Torch Theatre Company", label: "Torch Theatre Company" },
    { value: "Trafalgar UK Theatres", label: "Trafalgar UK Theatres" },
    { value: "Unicorn Theatre", label: "Unicorn Theatre" },
    { value: "Venue Cymru and Theatr Colwyn", label: "Venue Cymru and Theatr Colwyn" },
    { value: "Victoria Theatre Halifax", label: "Victoria Theatre Halifax" },
    { value: "Wales Millennium Centre", label: "Wales Millennium Centre" },
    { value: "Warwick Arts Centre", label: "Warwick Arts Centre" },
    { value: "Watermill Theatre", label: "Watermill Theatre" },
    { value: "Watford Palace Theatre", label: "Watford Palace Theatre" },
    { value: "Welsh National Opera", label: "Welsh National Opera" },
    { value: "Wilton's Music Hall", label: "Wilton's Music Hall" },
    { value: "Wiltshire Creative", label: "Wiltshire Creative" },
    { value: "Worthing Theatres", label: "Worthing Theatres" },
    { value: "Wycombe Swan", label: "Wycombe Swan" },
    { value: "Wyvern Theatre Swindon", label: "Wyvern Theatre Swindon" },
    { value: "York Theatre Royal", label: "York Theatre Royal" },
    { value: "Yvonne Arnaud Theatre", label: "Yvonne Arnaud Theatre" },
];

export default UKTVenues;
