const venues = [
	"Adelphi",
	"Aldwych",
	"Ambassadors",
	"Apollo",
	"Apollo Victoria",
	"Barbican",
	"Cambridge",
	"Criterion",
	"Dominion",
	"Duchess",
	"Duke of York's",
	"Fortune",
	"Garrick",
	"Gielgud",
	"Gillian Lynne",
	"Harold Pinter",
	"His Majesty's",
	"London Coliseum",
	"London Palladium",
	"Lyceum",
	"Lyric",
	"National Theatre",
	"Noël Coward",
	"Novello",
	"Palace",
	"Phoenix",
	"Piccadilly",
	"Playhouse",
	"Prince Edward",
	"Prince of Wales",
	"Regent's Park Open Air",
	"Royal Court (Jerwood Theatre Downstairs)",
	"Royal Opera House",
	"Sadler's Wells",
	"Savoy",
	"Shaftesbury",
	"Shakespeare's Globe",
	"@sohoplace",
	"Sondheim",
	"St Martin's",
	"Trafalgar Theatre",
	"The Old Vic",
	"Theatre Royal Drury Lane",
	"Theatre Royal Haymarket",
	"Vaudeville",
	"Victoria Palace",
	"Wyndham's"
];

export default venues;