const venues = [
    { value: "Adelphi", label: "Adelphi" },
    { value: "Aldwych", label: "Aldwych" },
    { value: "Ambassadors", label: "Ambassadors" },
    { value: "Apollo", label: "Apollo" },
    { value: "Apollo Victoria", label: "Apollo Victoria" },
    { value: "Barbican", label: "Barbican" },
    { value: "Barbican - The Pit", label: "Barbican - The Pit" },
    { value: "Cambridge", label: "Cambridge" },
    { value: "Chichester Festival Theatre", label: "Chichester Festival Theatre" },
    { value: "Chichester Minerva Theatre", label: "Chichester Minerva Theatre" },
    { value: "Criterion", label: "Criterion" },
    { value: "Dominion", label: "Dominion" },
    { value: "Duchess", label: "Duchess" },
    { value: "Duke of York's", label: "Duke of York's" },
    { value: "Fortune", label: "Fortune" },
    { value: "Garrick", label: "Garrick" },
    { value: "Gielgud", label: "Gielgud" },
    { value: "Gillian Lynne", label: "Gillian Lynne" },
    { value: "Harold Pinter", label: "Harold Pinter" },
    { value: "His Majesty's", label: "His Majesty's" },
    { value: "London Coliseum", label: "London Coliseum" },
    { value: "London Palladium", label: "London Palladium" },
    { value: "Lyceum", label: "Lyceum" },
    { value: "Lyric", label: "Lyric" },
    { value: "National Theatre Lyttelton", label: "National Theatre Lyttelton" },
    { value: "National Theatre Dorfman", label: "National Theatre Dorfman" },
    { value: "National Theatre Olivier", label: "National Theatre Olivier" },
    { value: "Noël Coward", label: "Noël Coward" },
    { value: "Novello", label: "Novello" },
    { value: "Palace", label: "Palace" },
    { value: "Phoenix", label: "Phoenix" },
    { value: "Piccadilly", label: "Piccadilly" },
    { value: "Playhouse", label: "Playhouse" },
    { value: "Prince Edward", label: "Prince Edward" },
    { value: "Prince of Wales", label: "Prince of Wales" },
    { value: "Regent's Park Open Air", label: "Regent's Park Open Air" },
    {
        value: "Royal Court (Jerwood Theatre Downstairs)",
        label: "Royal Court (Jerwood Theatre Downstairs)",
    },
    {
        value: "Royal Court (Jerwood Theatre Upstairs)",
        label: "Royal Court (Jerwood Theatre Upstairs)",
    },
    { value: "Royal Opera House Main Stage", label: "Royal Opera House Main Stage" },
    { value: "Royal Opera House Linbury Theatre", label: "Royal Opera House Linbury Theatre" },
    { value: "Sadler's Wells", label: "Sadler's Wells" },
    { value: "Savoy", label: "Savoy" },
    { value: "Shaftesbury", label: "Shaftesbury" },
    { value: "Shakespeare's Globe", label: "Shakespeare's Globe" },
    { value: "Sam Wanamaker Playhouse", label: "Sam Wanamaker Playhouse" },
    {
        value: "Southbank Centre Queen Elizabeth Hall",
        label: "Southbank Centre Queen Elizabeth Hall",
    },
    { value: "Southbank Centre Purcell Room", label: "Southbank Centre Purcell Room" },
    { value: "Southwark Playhouse Borough", label: "Southwark Playhouse Borough" },
    { value: "Southwark Playhouse Elephant", label: "Southwark Playhouse Elephant" },
    { value: "@sohoplace", label: "@sohoplace" },
    { value: "Sondheim", label: "Sondheim" },
    { value: "St Martin's", label: "St Martin's" },
    { value: "Trafalgar Theatre", label: "Trafalgar Theatre" },
    { value: "The Old Vic", label: "The Old Vic" },
    { value: "Theatre Royal Drury Lane", label: "Theatre Royal Drury Lane" },
    { value: "Theatre Royal Haymarket", label: "Theatre Royal Haymarket" },
    { value: "Vaudeville", label: "Vaudeville" },
    { value: "Victoria Palace", label: "Victoria Palace" },
    { value: "Wyndham's", label: "Wyndham's" },
];

export default venues;
