const venues = [
	{ value: "Adelphi", label: "Adelphi" },
	{ value: "Aldwych", label: "Aldwych" },
	{ value: "Ambassadors", label: "Ambassadors" },
	{ value: "Apollo", label: "Apollo" },
	{ value: "Apollo Victoria", label: "Apollo Victoria" },
	{ value: "Barbican", label: "Barbican" },
	{ value: "Cambridge", label: "Cambridge" },
	{ value: "Criterion", label: "Criterion" },
	{ value: "Dominion", label: "Dominion" },
	{ value: "Duchess", label: "Duchess" },
	{ value: "Duke of York's", label: "Duke of York's" },
	{ value: "Fortune", label: "Fortune" },
	{ value: "Garrick", label: "Garrick" },
	{ value: "Gielgud", label: "Gielgud" },
	{ value: "Gillian Lynne", label: "Gillian Lynne" },
	{ value: "Harold Pinter", label: "Harold Pinter" },
	{ value: "His Majesty's", label: "His Majesty's" },
	{ value: "London Coliseum", label: "London Coliseum" },
	{ value: "London Palladium", label: "London Palladium" },
	{ value: "Lyceum", label: "Lyceum" },
	{ value: "Lyric", label: "Lyric" },
	{ value: "National Theatre", label: "National Theatre" },
	{ value: "Noël Coward", label: "Noël Coward" },
	{ value: "Novello", label: "Novello" },
	{ value: "Palace", label: "Palace" },
	{ value: "Phoenix", label: "Phoenix" },
	{ value: "Piccadilly", label: "Piccadilly" },
	{ value: "Playhouse", label: "Playhouse" },
	{ value: "Prince Edward", label: "Prince Edward" },
	{ value: "Prince of Wales", label: "Prince of Wales" },
	{ value: "Regent's Park Open Air", label: "Regent's Park Open Air" },
	{ value: "Royal Court (Jerwood Theatre Downstairs)", label: "Royal Court (Jerwood Theatre Downstairs)" },
	{ value: "Royal Opera House", label: "Royal Opera House" },
	{ value: "Sadler's Wells", label: "Sadler's Wells" },
	{ value: "Savoy", label: "Savoy" },
	{ value: "Shaftesbury", label: "Shaftesbury" },
	{ value: "Shakespeare's Globe", label: "Shakespeare's Globe" },
	{ value: "@sohoplace", label: "@sohoplace" },
	{ value: "Sondheim", label: "Sondheim" },
	{ value: "St Martin's", label: "St Martin's" },
	{ value: "Trafalgar Theatre", label: "Trafalgar Theatre" },
	{ value: "The Old Vic", label: "The Old Vic" },
	{ value: "Theatre Royal Drury Lane", label: "Theatre Royal Drury Lane" },
	{ value: "Theatre Royal Haymarket", label: "Theatre Royal Haymarket" },
	{ value: "Vaudeville", label: "Vaudeville" },
	{ value: "Victoria Palace", label: "Victoria Palace" },
	{ value: "Wyndham's", label: "Wyndham's" },
];

export default venues;

"Adelphi, Aldwych, Ambassadors, Apollo, Apollo Victoria, Barbican, Cambridge, Criterion, Dominion, Duchess, Duke of York's, Fortune, Garrick, Gielgud, Gillian Lynne, Harold Pinter, His Majesty's, London Coliseum, London Palladium, Lyceum, Lyric, National Theatre, Noël Coward, Novello, Palace, Phoenix, Piccadilly, Playhouse, Prince Edward, Prince of Wales, Regent's Park Open Air, Royal Court (Jerwood Theatre Downstairs), Royal Opera House, Sadler's Wells, Savoy, Shaftesbury, Shakespeare's Globe, @sohoplace, Sondheim, St Martin's, Trafalgar Theatre, The Old Vic, Theatre Royal Drury Lane, Theatre Royal Haymarket, Vaudeville, Victoria Palace, Wyndham's, Adelphi, Aldwych, Ambassadors, Apollo, Apollo Victoria, Barbican, Cambridge, Criterion, Dominion, Duchess, Duke of York's, Fortune, Garrick, Gielgud, Gillian Lynne, Harold Pinter, His Majesty's, London Coliseum, London Palladium, Lyceum, Lyric, National Theatre, Noël Coward, Novello, Palace, Phoenix, Piccadilly, Playhouse, Prince Edward, Prince of Wales, Regent's Park Open Air, Royal Court (Jerwood Theatre Downstairs), Royal Opera House, Sadler's Wells, Savoy, Shaftesbury, Shakespeare's Globe, @sohoplace, Sondheim, St Martin's, Trafalgar Theatre, The Old Vic, Theatre Royal Drury Lane, Theatre Royal Haymarket, Vaudeville, Victoria Palace, Wyndham's"